name: Image - M42PL

on:
  workflow_run:
    workflows:
      - "Image - M42PL - Core"
    types:
      - completed

jobs:

  image-m42pl:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - name: Checkout m42pl-core
        uses: actions/checkout@v2
        with:
          path: m42pl-core

      - name: Checkout m42pl-commands
        uses: actions/checkout@v2
        with:
          repository: jpclipffel/m42pl-commands
          path: m42pl-commands

      - name: Checkout m42pl-dispatchers
        uses: actions/checkout@v2
        with:
          repository: jpclipffel/m42pl-dispatchers
          path: m42pl-dispatchers

      - name: Checkout m42pl-kvstores
        uses: actions/checkout@v2
        with:
          repository: jpclipffel/m42pl-kvstores
          path: m42pl-kvstores

      - name: Checkout m42pl-encoders
        uses: actions/checkout@v2
        with:
          repository: jpclipffel/m42pl-encoders
          path: m42pl-encoders

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build image and push to registries
        # For GitHub Packages, do not forget to allow the source repository
        # to push (role: write) at github.com/users/{user}/packages/container/{name}/settings
        uses: docker/build-push-action@v2
        with:
          context: .
          file: m42pl-core/images/m42pl/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/m42pl:latest
            ghcr.io/${{ github.actor }}/m42pl:latest
